remote_theme: pages-themes/merlot@v0.2.0
plugins:
title: PowerShell Slap Shot
author: Nathan Hamblin
description: This blog post is meant for development and testing. Not responsibile for the crazy things you are going to doing.  
