theme: Minima
title: PowerShell Slap Shot
author: Nathan Hamblin
description: This blog post is meant to share things to the community. Not responsible for unexpected things you might do.
url: https://nathan1824.github.io/
