theme: Minima
title: PowerShell Slap Shot
author: Nathan Hamblin, <a href="https://tech.lgbt/@NathanHamblin_MI6" rel="me">Follow me on Mastodon!</a>
description: This blog post is meant to share things to the community. Not responsible for unexpected things you might do.

