theme: Minima
title: PowerShell Slap Shot
author: Nathan Hamblin
description: This blog post is meant to share things to the community. Please validate and read code, not responsible for unexpected things you might do.

